# [START django_app]
runtime: python
env: flex
manual_scaling:
  instances: 4  # Adjust to a value less than or equal to 32
runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.8"
entrypoint: gunicorn -b :$PORT rqm.wsgi:application
env_variables:
  DEBUG : "True"
  DB_HOST : "34.29.63.25"
  DB_NAME : "reqmechdatabase"
  DB_PASSWORD : "@l=;Zu/=%&L=<OUx"
  DB_PORT : "5432"
  DB_USER : "reqmech"
  SECRET_KEY : "sysg0k&abo*_5e%vth+(zea7()%p0_3v5i1x"
  EMAIL_HOST : "smtp.eu.mailgun.org"
  EMAIL_HOST_PASSWORD : "Kred2023@@"
  EMAIL_HOST_USER : "support@mail.kredhq.com"
  EMAIL_PORT : "465"
handlers:
# This configures Google App Engine to serve the files in the app's
# static directory.
- url: /static
  static_dir: static/
# This handler routes all requests not caught above to the main app. 
# It is required when static routes are defined, but can be omitted 
# (along with the entire handlers section) when there are no static 
# files defined.
- url: /.*
  script: auto
# [END django_app]