version: "3.9"

services:
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"

  django:
    image: rqm-docker:0.0.1
    build: .
    command: sh -c "
        python manage.py runserver 0.0.0.0:8000 &&
    ports:
      - "80:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_PORT=${EMAIL_PORT}